FROM python:3.10-buster
WORKDIR /app
RUN apt install -y git && \
   git clone https://github.com/BharathSharath/python-project.git && \
   mv /app/python-project/* /app && \
   pip install -r requirements.txt && \
   python manage.py migrate
ENTRYPOINT python manage.py runserver 0.0.0.0:8732
EXPOSE 8732:8732
